spring:
  profiles:
    active: dev
    group:
      dev: "dev"
      prod: "prod"
      test: "test"
    include:
      - s3
      - security
      - redis
      - fastapi

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
      base-path: /pickle-actuator
  endpoint:
    health:
      enabled: true

fcm:
  certification: ${FCM_CERTIFICATION}