spring:
  datasource:
    url: ${H2_DATASOURCE_URL}
    username: ${H2_DATASOURCE_USERNAME}
    password: ${H2_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  profiles:
    include:
      - s3
      - security